Mention "canto_space/logs" in the documentation

diff --git a/script/canto_start_docker b/script/canto_start_docker
--- a/script/canto_start_docker
+++ b/script/canto_start_docker
@@ -29,6 +29,12 @@ then
    exit 1
 fi
 
+if [ ! -d logs ]
+then
+   echo 'missing "logs" directory - exiting'
+   exit 1
+fi
+
 if [ $(uname) = Linux ]
 then
     EXTRA_ARGS="--net=host --env=OWLTOOLS_MEMORY"
@@ -47,7 +53,7 @@ if [ "$1" == "--no-tty" ]; then
 fi
 
 
-CANTO_DOCKER_RUN_ARGS="$EXTRA_ARGS -i $TTY_OPT --rm $DEBUG --security-opt seccomp=unconfined --cap-add=SYS_PTRACE --mount type=bind,source=$(pwd)/data,target=/data --mount type=bind,source=$(pwd)/import_export,target=/import_export --mount type=bind,source=$(pwd)/canto,target=/canto -w=/canto pombase/canto-base:v12"
+CANTO_DOCKER_RUN_ARGS="$EXTRA_ARGS -i $TTY_OPT --rm $DEBUG --security-opt seccomp=unconfined --cap-add=SYS_PTRACE --mount type=bind,source=$(pwd)/logs,target=/logs  --mount type=bind,source=$(pwd)/data,target=/data --mount type=bind,source=$(pwd)/import_export,target=/import_export --mount type=bind,source=$(pwd)/canto,target=/canto -w=/canto pombase/canto-base:v12"
 
 cd canto
 
