Add logging to canto_docker script

diff --git a/script/canto_docker b/script/canto_docker
--- a/script/canto_docker
+++ b/script/canto_docker
@@ -18,6 +18,12 @@ then
    exit 1
 fi
 
+if [ ! -d logs ]
+then
+   echo 'missing "logs" directory - exiting'
+   exit 1
+fi
+
 EXTRA_ARGS=""
 
 if [ $(uname) = Linux ]
@@ -33,8 +39,10 @@ then
     INTERACTIVE_ARGS="--name canto"
 fi
 
-CANTO_DOCKER_RUN_ARGS="$EXTRA_ARGS --rm $INTERACTIVE_ARGS --mount type=bind,source=$(pwd)/data,target=/data --mount type=bind,source=$(pwd)/import_export,target=/import_export --mount type=bind,source=$(pwd)/canto,target=/canto -w=/canto pombase/canto-base:v12"
+CANTO_DOCKER_RUN_ARGS="$EXTRA_ARGS --rm $INTERACTIVE_ARGS --mount type=bind,source=$(pwd)/logs,target=/logs --mount type=bind,source=$(pwd)/data,target=/data --mount type=bind,source=$(pwd)/import_export,target=/import_export --mount type=bind,source=$(pwd)/canto,target=/canto -w=/canto pombase/canto-base:v12"
 
 cd canto
 
-exec docker run $CANTO_DOCKER_RUN_ARGS "$@"
+RUN_ARGS="$@ >> /logs/`date --rfc-3339=date`.log.txt 2>&1"
+
+exec docker run $CANTO_DOCKER_RUN_ARGS bash -c "$RUN_ARGS"
